# -------------------------------------------------------------------
# Helm Deployment Script Generator
#
# Because the ARO cluster API server is private, Helm must run from
# within the virtual network (e.g., from the jumpbox VM).  This file
# generates a ready-to-use deployment script that operators can
# execute on the jumpbox after Terraform provisions the infrastructure.
# -------------------------------------------------------------------

resource "local_file" "helm_deploy_script" {
  filename        = "${path.module}/../../deploy_platform.sh"
  file_permission = "0755"
  content         = <<-SCRIPT
#!/usr/bin/env bash
# =============================================================================
# Quantech Clinical Workflow Platform — Helm Deployment Script
# Generated by Terraform. Run this script from the jumpbox VM.
# =============================================================================
set -euo pipefail

CLUSTER_NAME="${var.aro_cluster_name}"
RESOURCE_GROUP="${var.spoke_rg_name}"
NAMESPACE="${var.helm_namespace}"
ACR_NAME=$(az acr list --resource-group "$RESOURCE_GROUP" --query "[0].name" -o tsv)

echo "==> Retrieving ARO cluster credentials..."
API_URL=$(az aro show --name "$CLUSTER_NAME" --resource-group "$RESOURCE_GROUP" \
  --query "apiserverProfile.url" -o tsv)
KUBEADMIN_PASS=$(az aro list-credentials --name "$CLUSTER_NAME" \
  --resource-group "$RESOURCE_GROUP" --query "kubeadminPassword" -o tsv)

echo "==> Logging in to OpenShift cluster..."
oc login "$API_URL" --username kubeadmin --password "$KUBEADMIN_PASS" \
  --insecure-skip-tls-verify=true

echo "==> Creating namespace '$NAMESPACE' (if not exists)..."
oc new-project "$NAMESPACE" 2>/dev/null || oc project "$NAMESPACE"

echo "==> Configuring ACR pull secret..."
ACR_SERVER=$(az acr show --name "$ACR_NAME" --query "loginServer" -o tsv)
ACR_USER=$(az acr credential show --name "$ACR_NAME" --query "username" -o tsv)
ACR_PASS=$(az acr credential show --name "$ACR_NAME" --query "passwords[0].value" -o tsv)

oc create secret docker-registry acr-secret \
  --docker-server="$ACR_SERVER" \
  --docker-username="$ACR_USER" \
  --docker-password="$ACR_PASS" \
  --namespace="$NAMESPACE" 2>/dev/null || \
  echo "    ACR pull secret already exists."

oc secrets link default acr-secret --for=pull --namespace="$NAMESPACE" 2>/dev/null || true

echo "==> Retrieving Azure SQL connection details from Key Vault..."
KV_NAME=$(az keyvault list --resource-group "$RESOURCE_GROUP" --query "[0].name" -o tsv)
SQL_CONN=$(az keyvault secret show --vault-name "$KV_NAME" \
  --name "sql-connection-string" --query "value" -o tsv)

%{if var.helm_chart_repository != "" && var.helm_chart_name != ""}
echo "==> Adding Helm repository..."
helm repo add quantech "${var.helm_chart_repository}"
helm repo update

echo "==> Deploying ${var.helm_chart_name} via Helm..."
helm upgrade --install "${var.helm_chart_name}" "quantech/${var.helm_chart_name}" \
  --namespace "$NAMESPACE" \
  %{if var.helm_chart_version != ""}--version "${var.helm_chart_version}" \%{endif}
  --set global.image.registry="$ACR_SERVER" \
  --set global.imagePullSecrets[0].name="acr-secret" \
  --set database.connectionString="$SQL_CONN" \
  --set frontdoor.enabled=true \
  --wait --timeout 10m
%{else}
echo "==> Helm chart repository/name not configured."
echo "    Set helm_chart_repository and helm_chart_name in Terraform variables."
echo ""
echo "    Example manual deployment:"
echo "      helm upgrade --install quantech-platform ./chart \\"
echo "        --namespace $NAMESPACE \\"
echo "        --set global.image.registry=$ACR_SERVER \\"
echo "        --set global.imagePullSecrets[0].name=acr-secret \\"
echo "        --set database.connectionString=\$SQL_CONN \\"
echo "        --set frontdoor.enabled=true"
%{endif}

echo ""
echo "==> Deployment complete."
echo "    Cluster console: $(az aro show --name "$CLUSTER_NAME" --resource-group "$RESOURCE_GROUP" --query "consoleProfile.url" -o tsv)"
echo "    Front Door endpoint: check Terraform outputs for AFD_endpoint_FQDN"
SCRIPT
}
